export type Country = { name: string; dialCode: string };

export const COUNTRIES: Country[] = [
  { name: 'Cameroon', dialCode: '+237' },
  { name: 'France', dialCode: '+33' },
  { name: 'United States', dialCode: '+1' },
  { name: 'United Kingdom', dialCode: '+44' },
  { name: 'Nigeria', dialCode: '+234' },
  { name: 'Senegal', dialCode: '+221' },
  { name: "Côte d'Ivoire", dialCode: '+225' },
  { name: 'Ghana', dialCode: '+233' },
  { name: 'South Africa', dialCode: '+27' },
  { name: 'Kenya', dialCode: '+254' },
  { name: 'Ethiopia', dialCode: '+251' },
  { name: 'Tanzania', dialCode: '+255' },
  { name: 'Uganda', dialCode: '+256' },
  { name: 'Rwanda', dialCode: '+250' },
  { name: 'Congo (DRC)', dialCode: '+243' },
  { name: 'Congo (Republic)', dialCode: '+242' },
  { name: 'Gabon', dialCode: '+241' },
  { name: 'Chad', dialCode: '+235' },
  { name: 'Central African Republic', dialCode: '+236' },
  { name: 'Equatorial Guinea', dialCode: '+240' },
  { name: 'Germany', dialCode: '+49' },
  { name: 'Belgium', dialCode: '+32' },
  { name: 'Switzerland', dialCode: '+41' },
  { name: 'Canada', dialCode: '+1' },
  { name: 'Brazil', dialCode: '+55' },
  { name: 'China', dialCode: '+86' },
  { name: 'India', dialCode: '+91' },
  { name: 'Japan', dialCode: '+81' },
  { name: 'Australia', dialCode: '+61' },
  { name: 'Morocco', dialCode: '+212' },
  { name: 'Algeria', dialCode: '+213' },
  { name: 'Tunisia', dialCode: '+216' },
  { name: 'Egypt', dialCode: '+20' },
  { name: 'Spain', dialCode: '+34' },
  { name: 'Italy', dialCode: '+39' },
  { name: 'Portugal', dialCode: '+351' },
  { name: 'Netherlands', dialCode: '+31' },
  { name: 'Russia', dialCode: '+7' },
  { name: 'Turkey', dialCode: '+90' },
  { name: 'Saudi Arabia', dialCode: '+966' },
  { name: 'UAE', dialCode: '+971' },
];
